spring.application.name=ai



# ==============================
# Hugging Face Configuration
# ==============================

# Change this line:
huggingface.base-url=https://router.huggingface.co/hf-inference/models/

huggingface.model=black-forest-labs/FLUX.1-dev

# Your API Key

huggingface.api.key=${API_KEY}



huggingface.connect-timeout=30



